### ISSUE TITLE
NPE when opening dialog

### ISSUE THREAD

**Issue by markiewb** [sickill/off-plugin#30]
```
java.lang.NullPointerException
	at net.sickill.off.netbeans.NetbeansIDE$1.actionPerformed(NetbeansIDE.java:61)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1332)
	at javax.swing.JComboBox.intervalRemoved(JComboBox.java:1352)
	at javax.swing.AbstractListModel.fireIntervalRemoved(AbstractListModel.java:179)
	at javax.swing.DefaultComboBoxModel.removeAllElements(DefaultComboBoxModel.java:174)
	at javax.swing.JComboBox.removeAllItems(JComboBox.java:771)
	at net.sickill.off.netbeans.NetbeansIDE.onFocus(NetbeansIDE.java:43)
	at net.sickill.off.common.OffPanel.focusOnDefaultComponent(OffPanel.java:145)
	at net.sickill.off.netbeans.NetbeansDialog.showDialog(NetbeansDialog.java:41)
	at net.sickill.off.netbeans.OpenOffAction.actionPerformed(OpenOffAction.java:27)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
```

**Comment by markiewb** [comment]
Fixed in 1.3
