### ISSUE TITLE
Exceptions when switching projects too fast

### ISSUE THREAD

**Issue by markiewb** [sickill/off-plugin#33]
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.sickill.off.common.OffListModel.getElementAt(OffListModel.java:192)
	at net.sickill.off.common.OffListModel.getElementAt(OffListModel.java:16)
	at javax.swing.plaf.basic.BasicListUI.paintCell(BasicListUI.java:204)
	at javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:317)
	at javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:240)
```

```
java.lang.NullPointerException
	at net.sickill.off.common.OffColumnCellRenderer.getListCellRendererComponent(OffColumnCellRenderer.java:43)
	at net.sickill.off.common.OffColumnCellRenderer.getListCellRendererComponent(OffColumnCellRenderer.java:18)
	at javax.swing.plaf.basic.BasicListUI.paintCell(BasicListUI.java:209)
	at javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:317)
	at javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:240)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
```

**Comment by markiewb** [comment]
Fixed in 1.3
